kimm_robot_node:
  ros__parameters:
    sim: true

    base_frame: "proximal_ring"
    platform_frame: "distal_ring"

    publish_rate_hz: 20.0

    # Home pose in ROS-native units.
    # Translation: meters
    # Rotation: radians
    home_tx_m: 0.0
    home_ty_m: 0.0
    home_tz_m: 0.0
    home_rx_rad: 0.0
    home_ry_rad: 0.0
    home_rz_rad: 0.0

    # Virtual joints from kimm_description.
    # These drive RViz visualization through /joint_states.
    platform_joint_names:
      - "platform_x_joint"
      - "platform_y_joint"
      - "platform_z_joint"
      - "platform_roll_joint"
      - "platform_pitch_joint"
      - "platform_yaw_joint"

    # Six actuator joints returned by KIMM IK.
    # These are published on /kimm/state/joints.
    actuator_joint_names:
      - "actuator_101"
      - "actuator_102"
      - "actuator_103"
      - "actuator_104"
      - "actuator_105"
      - "actuator_106"

kimm_hardware_bridge:
  ros__parameters:
    auto_activate: true
    zero_on_activate: true
    zero_position_counts: [2048, 2048, 2048, 2048, 2048, 2048]
    zero_after_torque_delay_sec: 0.10
    
    publish_rate_hz: 50.0
    deadband_rad: 0.00001

    hardware_port: "/dev/ttyUSB0"
    baudrate: 57600
    protocol_version: 2.0

    dxl_ids: [101, 102, 103, 104, 105, 106]
    dxl_center: 2048

    dxl_odd_min: 1707
    dxl_odd_max: 2389
    dxl_even_min: 1707
    dxl_even_max: 2389